# Generated by Django 4.2.6 on 2023-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='No_of_guests',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Inventory',
        ),
    ]
